Fix string interpolation in bin/deploy

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -5,9 +5,9 @@ DEPLOY_BRANCH=gh-pages
 # Jekyll will not allow custom ENV variables like JEKYLL_ENV when in the
 # gh-pages branch, so I need to go to another branch, build it, then merge
 # it into gh-pages.
-echo "> git checkout $(INTERMEDIARY_BRANCH)"
+echo "> git checkout $INTERMEDIARY_BRANCH"
 git checkout $INTERMEDIARY_BRANCH 2>/dev/null || git checkout -b $INTERMEDIARY_BRANCH
-if [[ $? != 0 ]]; then echo "Cannot checkout $(INTERMEDIARY_BRANCH)"; exit 1; fi
+if [[ $? != 0 ]]; then echo "Cannot checkout $INTERMEDIARY_BRANCH"; exit 1; fi
 
 echo "> git merge master --no-edit"
 git merge master --no-edit
@@ -28,15 +28,15 @@ if [[ $? != 0 ]]; then echo "Cannot add files to stage."; exit $?; fi
 echo "> git commit -m \"Deploy\""
 git commit -m "Deploy"
 
-echo "> git checkout $(DEPLOY_BRANCH)"
+echo "> git checkout $DEPLOY_BRANCH"
 git checkout $DEPLOY_BRANCH
-if [[ $? != 0 ]]; then echo "Cannot checkout $(DEPLOY_BRANCH)"; exit 1; fi
+if [[ $? != 0 ]]; then echo "Cannot checkout $DEPLOY_BRANCH"; exit 1; fi
 
-echo "> git merge $(INTERMEDIARY_BRANCH) --no-edit"
+echo "> git merge $INTERMEDIARY_BRANCH --no-edit"
 git merge $INTERMEDIARY_BRANCH --no-edit
 if [[ $? != 0 ]]; then echo "Cannot merge intermediary cleanly. Please fix conflicts and try again."; exit $?; fi
 
-echo "> git push origin $(DEPLOY_BRANCH) --force"
+echo "> git push origin $DEPLOY_BRANCH --force"
 git push origin $DEPLOY_BRANCH --force
 if [[ $? != 0 ]]; then echo "Cannot push to Github."; exit $?; fi
 
