Makes sure git merge failures exit

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -2,18 +2,34 @@
 
 echo "> git checkout gh-pages"
 git checkout gh-pages
+if [[ $? != 0 ]]; then echo "Cannot checkout"; exit 1; fi
+
 echo "> git merge master --no-edit"
 git merge master --no-edit
+if [[ $? != 0 ]]; then echo "Cannot merge cleanly. Please fix conflicts and try again."; exit $?; fi
+
 echo "> JEKYLL_ENV=production bundle exec jekyll build"
 JEKYLL_ENV=production bundle exec jekyll build
+if [[ $? != 0 ]]; then echo "Cannot build."; exit $?; fi
+
 echo "> rsync -a -I _site/ ./"
 rsync -a -I _site/ ./
+if [[ $? != 0 ]]; then echo "Cannot rsync."; exit $?; fi
+
 echo "> git add . -u"
 git add . -u
+if [[ $? != 0 ]]; then echo "Cannot add files to stage."; exit $?; fi
+
 echo "> git commit -m \"Deploy\""
 git commit -m "Deploy"
+if [[ $? != 0 ]]; then echo "Cannot commit."; exit $?; fi
+
 echo "> git push origin gh-pages --force"
 git push origin gh-pages --force
+if [[ $? != 0 ]]; then echo "Cannot push to Github."; exit $?; fi
+
 echo "> git checkout master"
 git checkout master
+if [[ $? != 0 ]]; then echo "Cannot checkout master."; exit $?; fi
+
 echo "Deployed to http://alexsquest.com"
