Uses intermediary branch to build gh-pages

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
 
+# Jekyll will not allow custom ENV variables like JEKYLL_ENV when in the
+# gh-pages branch, so I need to go to another branch, build it, then merge
+# it into gh-pages.
 echo "> git checkout deploy-custom-html"
 git checkout deploy-custom-html
-if [[ $? != 0 ]]; then echo "Cannot checkout"; exit 1; fi
+if [[ $? != 0 ]]; then echo "Cannot checkout deploy-custom-html"; exit 1; fi
 
 echo "> git merge master --no-edit"
 git merge master --no-edit
@@ -23,8 +26,16 @@ if [[ $? != 0 ]]; then echo "Cannot add files to stage."; exit $?; fi
 echo "> git commit -m \"Deploy\""
 git commit -m "Deploy"
 
-echo "> git push origin deploy-custom-html --force"
-git push origin deploy-custom-html --force
+echo "> git checkout gh-pages"
+git checkout gh-pages
+if [[ $? != 0 ]]; then echo "Cannot checkout gh-pages"; exit 1; fi
+
+echo "> git merge deploy-custom-html --no-edit"
+git merge deploy-custom-html --no-edit
+if [[ $? != 0 ]]; then echo "Cannot merge intermediary cleanly. Please fix conflicts and try again."; exit $?; fi
+
+echo "> git push origin gh-pages --force"
+git push origin gh-pages --force
 if [[ $? != 0 ]]; then echo "Cannot push to Github."; exit $?; fi
 
 echo "> git checkout master"
